spring.application.name=terralog
spring.datasource.url=jdbc:mysql://localhost:3306/terralog
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true